Repository RobotWebTools/web_video_server, pull requests merged in 2024-10, with the labels that each got.

#150 Fix usage of deprecated libavcodec functions
  include/web_video_server/libav_streamer.h
  src/image_streamer.cpp
  src/libav_streamer.cpp
Labels: bug, ros2

#118 Add link to /stream in stream list
  src/web_video_server.cpp
Labels: enhancement, ros1

#106 Add Support For Alpha PNGs
  include/web_video_server/image_streamer.h
  include/web_video_server/png_streamers.h
  src/image_streamer.cpp
  src/png_streamers.cpp
Labels: enhancement, ros1

#161 Add license headers to all C++ source files, update copyrights
  CMakeLists.txt
  CONTRIBUTING.md
  LICENSE
  include/web_video_server/h264_streamer.hpp
  include/web_video_server/image_streamer.hpp
  include/web_video_server/jpeg_streamers.hpp
  include/web_video_server/libav_streamer.hpp
  include/web_video_server/multipart_stream.hpp
  include/web_video_server/png_streamers.hpp
  include/web_video_server/ros_compressed_streamer.hpp
  include/web_video_server/utils.hpp
  include/web_video_server/vp8_streamer.hpp
  include/web_video_server/vp9_streamer.hpp
  include/web_video_server/web_video_server.hpp
  package.xml
  src/h264_streamer.cpp
  src/image_streamer.cpp
  src/jpeg_streamers.cpp
  src/libav_streamer.cpp
  src/multipart_stream.cpp
  src/png_streamers.cpp
  src/ros_compressed_streamer.cpp
  src/utils.cpp
  src/vp8_streamer.cpp
  src/vp9_streamer.cpp
  src/web_video_server.cpp
Labels: enhancement, ros2
